courses/urls.py
from django.urls import path

from . import views

app_name = "courses"
urlpatterns = [
    path('', views.index, name="index"),
    path('<c_id>', views.course, name="course"),
    path('<c_id>/book', views.books, name="book"),
    path('<c_id>/cancel', views.cancel_enrollment,name="cancel"),
    path('<c_id>', views.course, name="check_courses"),

]

quota_Register/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path

from . import views
from courses import views as views1

app_name="users"
urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

courses/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Course(models.Model):
    c_id = models.CharField(max_length=5 , primary_key=True)
    c_name = models.CharField(max_length=64)
    
    semestry_choices = [("1","1"),("1","2"),]
    
    semestry = models.CharField(max_length = 5, choices = semestry_choices, default = "")
    year = models.PositiveIntegerField()
    vacancy = models.PositiveIntegerField()
    
    OPEN = 'OPEN'
    CLOSE = 'CLOSE'
    status_choices = [('OPEN','OPEN'),('CLOSE','CLOSE')]
    
    status = models.CharField(max_length = 5, choices = status_choices, default = "CLOSE")
    students = models.ManyToManyField(User, blank=True, related_name="course")
    
    def __str__(self):
        return f"Course ID: {self.c_id}, Name:{self.c_name}"
        

users/models.py
from django.db import models

# Create your models here.

courses/views.py
from django.shortcuts import render, get_object_or_404 ,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages


# Create your views here.

from .models import Course
from users.views import *

def index(request):
    return render(request, "courses/index.html", {
        "courses": Course.objects.all()
    })


def course(request, c_id):
    course = get_object_or_404(Course, pk=c_id)
    student_count = course.students.all().count()
    status = course.status
    if request.user.is_superuser:
        return render(request, "courses/course_admin.html", {
        "course": course,
        "students": course.students.all(),
        "student_count": student_count,
        "status": status,
        })
    else:
        return render(request, "courses/course.html", {
        "course": course,
        "students": course.students.all(),
        "student_count": student_count,
        })


def books(request, c_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))

    course = get_object_or_404(Course, pk=c_id)
    if request.user not in course.students.all():
        if course.students.all().count() < course.vacancy and course.status == "OPEN":
            course.students.add(request.user)


    return HttpResponseRedirect(reverse("courses:course", args=(c_id,)))


def cancel_enrollment(request, c_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))

    course = get_object_or_404(Course, pk=c_id)
    if request.user in course.students.all():
        course.students.remove(request.user)


    return HttpResponseRedirect(reverse("courses:course", args=(c_id,)))

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
from courses.models import Course

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    student_subject =  request.user.course.all()    
    return render(request, "users/index.html", {
        "student_subject": student_subject,
    })


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid credential."
            })
    
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    
    return render(request, "users/login.html", {
        "message": "Logged out."
    })
    

courses/templates/courses/course.html
{% extends "courses/layout.html" %}

{% block body %}

   <h1>Course: {{ course.c_id }}</h1>
   
   <ul>
       <li>Name: {{ course.c_name }}</li>
       <li>Semestry: {{ course.semestry }}</li>
       <li>Year: {{ course.year }}</li>
       <li>vacancy: {{ student_count }}/{{ course.vacancy }}</li>
       <li>Status: {{ course.status }}</li>
   </ul>
   
       <p><button type="button"><a href="{% url 'courses:book' course.c_id %}">Enroll Course</a></button></p>
       <p><button type="button"><a href="{% url 'courses:cancel' course.c_id %}">Cancel Enrollment</a></button></p>
       <p><button type="button"><a href="{% url 'courses:index' %}">Course List</a></button></p>
       <p><button type="button"><a href="{% url 'users:index' %}" >back home</a></button></p>
{% endblock %}

courses/templates/courses/course_admin.html
{% extends "courses/layout.html" %}

{% block body %}

   <h1>Course: {{ course.c_id }}</h1>

   <ul>
       <li>Name: {{ course.c_name }}</li>
       <li>Semestry: {{ course.semestry }}</li>
       <li>Year: {{ course.year }}</li>
       <li>Vacancy: {{ student_count }}/{{ course.vacancy }}</li>
       <li>Status: {{ status }}</li>
   </ul>

   <h3>Student:</h3>

   <ul>
       {% for i in students %}
           <li>{{ i.first_name }} {{ i.last_name }}</li>
       {% empty %}
           <li>No applicants</li>
       {% endfor %}
   </ul>

       <p><button type="button"><a href="{% url 'courses:book' course.c_id %}">Enroll Course</a></button></p>
       <p><button type="button"><a href="{% url 'courses:cancel' course.c_id %}">Cancel Enrollment</a></button></p>
       <p><button type="button"><a href="{% url 'courses:index' %}">Course List</a></button></p>
       <p><button type="button"><a href="{% url 'users:index' %}" >back home</a></button></p>
{% endblock %}

courses/templates/courses/index.html
{% extends "courses/layout.html" %}

{% block body %}

    <h1>Course List</h1>

    <ul>
    {% for course in courses %}
        <li><a href="{% url 'courses:course' course.c_id %}">{{ course }}<</li>
    {% endfor %}
    </ul>
    
    <ul>
        <p><button type="button" ><a href="{% url 'users:index' %}">back home</a></button></p>
    </ul>

{% endblock %}

courses/templates/courses/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Courses</title>
    </head>
    <style>
        .button {
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;
}
    </style>
    <body style="background-color:powderblue;">
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/index.html
{% extends "users/layout.html" %}

{% block body %}
    
    <h2>Welcome, {{ request.user.first_name }} {{ request.user.last_name }}</h2>
    
    <ul>
        <li >Username: {{ request.user.username }}</li>
        <li >Email: {{ request.user.email }}</li>
        
        <h3>Registered Courses</h3>
             {% for i in student_subject %}
                  <li>{{ i }}</li>
             {% empty %}
                  <li>No enrollment</li>
             {% endfor %}
    </ul>
    
    
    <p><button type="button"><a href="{% url 'courses:index' %}">Check Courses</a></button></p>
    <p><button type="button"><a href="{% url 'users:logout' %}">Logout</a></button></p>
    
    
{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Log in | Users</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </head>
    <style>
     
        .button {
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;
}
    </style>
    <body style="background-color:powderblue;">
        <div id="container">
            <div class="main shifted" id="main">
             
                    {% block body %}
                    {% endblock %}
                
            </div>
        </div>
    </body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}

    {% if message %}
        {{ message }}
    {% endif %}
    <h3 class="text-center text-wite pt-5">Users Login</h3>
    <div id="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="text-info">Username:</label><br>
                    <input type="text" name="username" id="username" class="form-control">
                </div>
                <div class="form-group">
                    <label for="password" class="text-info">Password:</label><br>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <div class="submit-group">
                    <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                </div>
            </form>
        </div>
    </div>

{% endblock %}